---
title: "Tecnologias da Informação e da Comunicação"
description: |
  Turma 2021.1
site: distill::distill_article

---

Este é o site do curso Tecnologias da Informação e da Comunicação, ESPM Rio, turma 2021.1.

Aqui, concentraremos o material de aula e referências para o curso. 

Este espaço não substitui o [Canvas](http://canvas.espm.br). Qualquer dúvida, 
entrem em contato por ele ou através do [e-mail do professor](mailto:lmancini@espm.br).

---

# Aulas 

#### Aula 1

[Introdução - o que é tecnologia?](https://tic.mancini.jor.br/aulas/Aula-1---Tecnologia-e-cotidiano.html)<br>


#### Aula 2 <br>
[Programas e Programação.](https://tic.mancini.jor.br/aulas/Aula-2---Programas-e-programacao.html)<br>


#### Aula 3 <br>
[Sistemas de Informação e de Comunicação](https://tic.mancini.jor.br/aulas/Aula-3---Sistemas.html)<br>

#### Aula 4 <br>
[Analógico e Digital](https://tic.mancini.jor.br/aulas/Aula-4---Analogico_Digital.html)<br>


#### Aula 5 <br>
[Estrutura Básica de Computadores](https://tic.mancini.jor.br/aulas/Aula-5---Redes.html)<br>

#### Aula 6 <br>
[TCP/IP](https://tic.mancini.jor.br/aulas/Aula_6_-_servicos.html)<br>

<!-- #### Aula 9 <br> -->
<!-- [IP e dominios](\aulas\Aula_9_-_servicos.html)<br> -->

<!-- #### Aula 10 <br> -->
<!-- [Estudo de caso: investigando e-mails](\aulas\Aula_10_-_estudo_de_caso.html)<br> -->

<!-- #### Aula 11 -->
<!-- [Segurança, Privacidade e Anonimidade](\aulas\Aula_11_-_seguranca.html)<br> -->

<!-- #### Aula 12 <br> -->
<!-- [Privacidade e anonimidade](\aulas\Aula_12_-_seguranca.html)<br> -->

<!-- #### Aula 13 <br> -->
<!-- [Criptografia](\aulas\Aula_13_-_criptografia.html)<br> -->


<!-- #### Aula 14 <br> -->
<!-- [Privacidade](\aulas\Aula_14_-_privacidade.html) <br> -->

<!-- #### Aula 15 <br> -->
<!-- [HTML básico](\aulas\Aula_15_-html-1.html)<br> -->


<!-- #### Aula 16 <br> -->
<!-- [HTML básico - aula 2](\aulas\Aula_16_-html-2-parte.html)<br> -->

<!-- #### Aula 17 <br> -->
<!-- [Ferramentas de publicação](\aulas\Aula_17_-ferramentas_pub.html)<br> -->
<!-- 19 de maio<br> -->

---

# Aula a aula 
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;text-align: center;"> Dia </th>
   <th style="text-align:left;text-align: center;"> Tema </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 8-fev </td>
   <td style="text-align:left;background-color: white !important;"> Apresentação / Tecnologia e Cotidiano </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;color: white !important;background-color: #D7261E !important;"> 15-fev </td>
   <td style="text-align:left;background-color: white !important;color: white !important;background-color: #D7261E !important;"> Carnaval </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 22-fev </td>
   <td style="text-align:left;background-color: white !important;"> Programas e Programação / TIC </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;background-color: #E0EEEE !important;"> 1-mar </td>
   <td style="text-align:left;background-color: white !important;background-color: #E0EEEE !important;"> Seminários </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 8-mar </td>
   <td style="text-align:left;background-color: white !important;"> Sistemas / Analógico e digital </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 15-mar </td>
   <td style="text-align:left;background-color: white !important;"> Arquitetura de computadores e sistemas operacionais </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 22-mar </td>
   <td style="text-align:left;background-color: white !important;"> TCP/IP, Dominimo e hospedagem </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;background-color: #E0EEEE !important;"> 5-abr </td>
   <td style="text-align:left;background-color: white !important;background-color: #E0EEEE !important;"> Estudo de caso </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 12-abr </td>
   <td style="text-align:left;background-color: white !important;"> Segurança da Informação e criptografia </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;background-color: #E0EEEE !important;"> 19-abr </td>
   <td style="text-align:left;background-color: white !important;background-color: #E0EEEE !important;"> Prova </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;background-color: #FFFACD !important;"> 26-abr </td>
   <td style="text-align:left;background-color: white !important;background-color: #FFFACD !important;"> Desentoca </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 3-mai </td>
   <td style="text-align:left;background-color: white !important;"> Correção da prova </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 10-mai </td>
   <td style="text-align:left;background-color: white !important;"> Introdução ao html e construção de páginas </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 17-mai </td>
   <td style="text-align:left;background-color: white !important;"> Introdução ao html e construção de páginas </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;background-color: #E0EEEE !important;"> 24-mai </td>
   <td style="text-align:left;background-color: white !important;background-color: #E0EEEE !important;"> Exercício prático html </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;"> 31-mai </td>
   <td style="text-align:left;background-color: white !important;"> Lab trabalho final </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;background-color: #E0EEEE !important;"> 7-jun </td>
   <td style="text-align:left;background-color: white !important;background-color: #E0EEEE !important;"> Entrega trabalho final </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;background-color: white !important;background-color: #E0EEEE !important;"> 14-jun </td>
   <td style="text-align:left;background-color: white !important;background-color: #E0EEEE !important;"> Prova Substitutiva </td>
  </tr>
</tbody>
</table>



---


# Avaliações

<table class="table table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
 <thead>
  <tr>
   <th style="text-align:left;text-align: center;"> Avaliações </th>
   <th style="text-align:center;text-align: center;"> % </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;width: 25em; background-color: white !important;"> Prova </td>
   <td style="text-align:center;background-color: white !important;"> 30% </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 25em; background-color: white !important;"> Trabalho </td>
   <td style="text-align:center;background-color: white !important;"> 20% </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 25em; background-color: white !important;"> Seminário </td>
   <td style="text-align:center;background-color: white !important;"> 10% </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 25em; background-color: white !important;"> Exercícios </td>
   <td style="text-align:center;background-color: white !important;"> 40% </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 25em; background-color: white !important;background-color: #E0EEEE !important;"> Extra </td>
   <td style="text-align:center;background-color: white !important;background-color: #E0EEEE !important;"> 1 pt </td>
  </tr>
</tbody>
<tfoot>
<tr><td style="padding: 0; " colspan="100%"><span style="font-style: italic;">Note: </span></td></tr>
<tr><td style="padding: 0; " colspan="100%">
<sup></sup> Extra: [Codeacademy](https://www.codecademy.com/learn/learn-html/modules/learn-html-elements)</td></tr>
</tfoot>
</table> 



